#![feature(array_map)]

mod russian_doll_envelopes;
mod palindrome_partitioning_ii;
mod reducing_dishes;
mod max_sum_of_three_subarrays;
mod max_sum_submatrix;
mod is_scramble;
mod number_of_arithmetic_slices;
mod two_sum;
mod find_all_concatenated_words_in_a_dict;
mod get_skyline;
mod min_absolute_sum_diff;
mod min_insertions;
mod can_partition_k_subsets;
mod minimum_time_required;
mod group_anagrams;
mod count_palindromic_subsequences;
mod min_stickers;
mod max_frequency;
mod strange_printer;
mod split_array_same_average;
mod profitable_schemes;
mod super_egg_drop;
mod split_array;
mod paint_house_i;
mod paint_house_iii;
mod find_rotate_steps;
mod pizza_with_3n_slices;
